stages:
  - build-api
  - build-ui

image:
  name: gcr.io/kaniko-project/executor:v1.24.0-debug
  entrypoint: [""]

variables:
  UI_BUILD_ARG_APP_NAME: "Proptimus"
  UI_BUILD_ARG_API_URL: "https://api.proptimus.biodata.ceitec.cz"
  UI_BUILD_DEVEL_ARG_API_URL: "https://api.devel.proptimus.biodata.ceitec.cz"

build-prod-api-image:
  stage: build-api
  script:
    - /kaniko/executor \
        --context "${CI_PROJECT_DIR}/api/proptimus-api" \
        --dockerfile Dockerfile \
        --destination "${CI_REGISTRY_IMAGE}/api:latest \
        --cache=true \
        --cache-ttl=168h \
        --snapshot-mode=redo \
        --compressed-caching=false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

build-devel-api-image:
  stage: build-api
  script:
    - /kaniko/executor \
        --context "${CI_PROJECT_DIR}/api/proptimus-api" \
        --dockerfile Dockerfile \
        --destination "${CI_REGISTRY_IMAGE}/api:${CI_COMMIT_REF_SLUG}" \
        --cache=true \
        --cache-ttl=168h \
        --snapshot-mode=redo \
        --compressed-caching=false
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"'

build-prod-ui-image:
  stage: build-ui
  needs:
    - build-prod-api-image
  script:
    - /kaniko/executor \
        --context "${CI_PROJECT_DIR}/ui/proptimus-ui" \
        --dockerfile Dockerfile \
        --build-arg NEXT_PUBLIC_APP_NAME="${UI_BUILD_ARG_APP_NAME}" \
        --build-arg NEXT_PUBLIC_API_URL="${UI_BUILD_ARG_API_URL}" \
        --destination "${CI_REGISTRY_IMAGE}/ui:latest \
        --cache=true \
        --cache-ttl=168h \
        --snapshot-mode=redo \
        --compressed-caching=false
  rules:
    - if: '$CI_COMMIT_BRANCH == "master"'

build-devel-ui-image:
  stage: build-ui
  needs:
    - build-devel-api-image
  script:
    - /kaniko/executor \
        --context "${CI_PROJECT_DIR}/ui/proptimus-ui" \
        --dockerfile Dockerfile \
        --build-arg NEXT_PUBLIC_APP_NAME="${UI_BUILD_ARG_APP_NAME}" \
        --build-arg NEXT_PUBLIC_API_URL="${UI_BUILD_DEVEL_ARG_API_URL}" \
        --destination "${CI_REGISTRY_IMAGE}/ui:${CI_COMMIT_REF_SLUG}" \
        --cache=true \
        --cache-ttl=168h \
        --snapshot-mode=redo \
        --compressed-caching=false
  rules:
    - if: '$CI_COMMIT_BRANCH != "master" && $CI_PIPELINE_SOURCE == "push"'
