apiVersion: v1
kind: Service
metadata:
  name: {{ include "proptimus.fullname" . }}-ui
  labels:
    {{- include "proptimus.labels" (dict "root" . "component" "ui") | nindent 4 }}
  {{- with .Values.ui.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.ui.service.type }}
  selector:
    {{- include "proptimus.selectorLabels" (dict "root" . "component" "ui") | nindent 4 }}
  ports:
    - name: http
      port: {{ .Values.ui.service.port }}
      targetPort: http
      protocol: TCP


