/**
 * Copyright (c) 2025 mol* contributors, licensed under MIT, See LICENSE file for more info.
 *
 * @author Generated by Droid
 */

import { PluginBehavior } from "molstar/lib/mol-plugin/behavior/behavior";
import { optimizationDifferenceLabelProvider } from "./label";
import { OptimizationDifferenceColorThemeProvider } from "./color";

export const OptimizationDifference = PluginBehavior.create<{}>({
  name: "optimization-difference",
  category: "misc",
  display: {
    name: "Optimization Difference",
    description:
      "Color theme for visualizing atom-level optimization differences from AlphaFoldDB structure predictions.",
  },
  ctor: class extends PluginBehavior.Handler<{}> {
    private labelProvider = optimizationDifferenceLabelProvider.getProvider();

    register(): void {
      this.ctx.representation.structure.themes.colorThemeRegistry.add(
        OptimizationDifferenceColorThemeProvider
      );
      this.ctx.managers.lociLabels.addProvider(this.labelProvider);
    }

    unregister(): void {
      this.ctx.representation.structure.themes.colorThemeRegistry.remove(
        OptimizationDifferenceColorThemeProvider
      );
      this.ctx.managers.lociLabels.removeProvider(this.labelProvider);
    }
  },
  params: () => ({}),
});
