/**
 * Copyright (c) 2025 mol* contributors, licensed under MIT, See LICENSE file for more info.
 *
 * @author Generated by Droid
 */

import { Color, ColorScale } from 'molstar/lib/mol-util/color';
import { StructureElement, Unit, Bond, StructureProperties } from 'molstar/lib/mol-model/structure';
import { Location } from 'molstar/lib/mol-model/location';
import { ParamDefinition as PD } from 'molstar/lib/mol-util/param-definition';
import { ColorTheme } from 'molstar/lib/mol-theme/color';
import { ColorThemeCategory } from 'molstar/lib/mol-theme/color/categories';
import { ThemeDataContext } from 'molstar/lib/mol-theme/theme';

const DefaultColor = Color(0xCCCCCC);
const Description = `Colors atoms and bonds by optimization difference value. White indicates 0.0 difference, blue indicates 3.0 or greater.`;

export const OptimizationDifferenceColorThemeParams = {
    data: PD.ObjectList({
        chain_id: PD.Text(''),
        residue_id: PD.Numeric(0),
        atom_id: PD.Text(''),
        value: PD.Numeric(0),
    }, e => `${e.chain_id}:${e.residue_id}:${e.atom_id}=${e.value.toFixed(2)}`),
    domain: PD.Interval([0, 3]),
};
export type OptimizationDifferenceColorThemeParams = typeof OptimizationDifferenceColorThemeParams

export function getOptimizationDifferenceColorThemeParams(ctx: ThemeDataContext) {
    return PD.clone(OptimizationDifferenceColorThemeParams);
}

interface OptimizationDataEntry {
    chain_id: string;
    residue_id: number;
    atom_id: string;
    value: number;
}

function createDataMap(data: OptimizationDataEntry[]): Map<string, number> {
    const map = new Map<string, number>();
    for (const entry of data) {
        const key = `${entry.chain_id}:${entry.residue_id}:${entry.atom_id}`;
        map.set(key, entry.value);
    }
    return map;
}

export function OptimizationDifferenceColorTheme(
    ctx: ThemeDataContext,
    props: PD.Values<OptimizationDifferenceColorThemeParams>
): ColorTheme<OptimizationDifferenceColorThemeParams> {
    const scale = ColorScale.create({
        reverse: false,
        domain: props.domain,
        listOrName: [[Color(0xFFFFFF), 0], [Color(0x0000FF), 1]],
        minLabel: props.domain[0].toString(),
        maxLabel: props.domain[1].toString(),
    });

    const dataMap = createDataMap(props.data);

    // Create a reusable location for bond coloring
    const l = ctx.structure ? StructureElement.Location.create(ctx.structure) : undefined;

    function getDifference(location: StructureElement.Location): number | undefined {
        if (!Unit.isAtomic(location.unit)) return undefined;

        const chainId = StructureProperties.chain.label_asym_id(location);
        const residueId = StructureProperties.residue.label_seq_id(location);
        const atomId = StructureProperties.atom.label_atom_id(location);

        const key = `${chainId}:${residueId}:${atomId}`;
        return dataMap.get(key);
    }

    function color(location: Location): Color {
        let diff: number | undefined;

        if (StructureElement.Location.is(location)) {
            diff = getDifference(location);
        } else if (Bond.isLocation(location) && l) {
            // For bonds, use the difference value from atom A
            l.unit = location.aUnit;
            l.element = location.aUnit.elements[location.aIndex];
            diff = getDifference(l);
        }

        if (diff === undefined) return DefaultColor;
        return scale.color(diff);
    }

    return {
        factory: OptimizationDifferenceColorTheme,
        granularity: 'group',
        preferSmoothing: true,
        color,
        props,
        description: Description,
        legend: scale.legend,
    };
}

export const OptimizationDifferenceColorThemeProvider: ColorTheme.Provider<OptimizationDifferenceColorThemeParams, 'optimization-difference'> = {
    name: 'optimization-difference',
    label: 'Optimization Difference',
    category: ColorThemeCategory.Misc,
    factory: OptimizationDifferenceColorTheme,
    getParams: getOptimizationDifferenceColorThemeParams,
    defaultValues: PD.getDefaultValues(OptimizationDifferenceColorThemeParams),
    isApplicable: (ctx: ThemeDataContext) => !!ctx.structure,
};
