/**
 * Copyright (c) 2025 mol* contributors, licensed under MIT, See LICENSE file for more info.
 *
 * @author Generated by Droid
 */

import { StructureElement, StructureProperties, Unit } from 'molstar/lib/mol-model/structure';
import { Loci } from 'molstar/lib/mol-model/loci';
import { LociLabelProvider } from 'molstar/lib/mol-plugin-state/manager/loci-label';
import { Coloring } from '../types';

export interface OptimizationDataEntry {
    chain_id: string;
    residue_id: number;
    atom_id: string;
    value: number;
}

function createDataMap(data: OptimizationDataEntry[]): Map<string, number> {
    const map = new Map<string, number>();
    for (const entry of data) {
        const key = `${entry.chain_id}:${entry.residue_id}:${entry.atom_id}`;
        map.set(key, entry.value);
    }
    return map;
}

export class OptimizationDifferenceLabelProvider {
    private dataMap: Map<string, number> = new Map();
    private _granularity: string = 'element';
    private _coloring: Coloring["kind"] = 'element-symbol';

    setData(data: OptimizationDataEntry[]) {
        this.dataMap = createDataMap(data);
    }

    setGranularity(granularity: string) {
        this._granularity = granularity;
    }

    setColoring(coloring: Coloring["kind"]) {
        this._coloring = coloring;
    }

    private _shouldShowLabel(): boolean {
        return this._granularity === 'element' && this._coloring === 'optimization-difference';
    }

    getProvider(): LociLabelProvider {
        return {
            label: (loci: Loci) => {
                if (!this._shouldShowLabel()) return;

                if (!StructureElement.Loci.is(loci)) return;

                const loc = StructureElement.Loci.getFirstLocation(loci);
                if (!loc || !Unit.isAtomic(loc.unit)) return;

                const chainId = StructureProperties.chain.label_asym_id(loc);
                const residueId = StructureProperties.residue.label_seq_id(loc);
                const atomId = StructureProperties.atom.label_atom_id(loc);

                const key = `${chainId}:${residueId}:${atomId}`;
                const value = this.dataMap.get(key);

                if (value === undefined) return;

                return `<b>Optimization Difference:</b> ${value.toFixed(3)}`;
            }
        };
    }
}

export const optimizationDifferenceLabelProvider = new OptimizationDifferenceLabelProvider();
